# Generated by Django 5.1.6 on 2025-03-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
